### ISSUE TITLE
Week03 : Experiment Missing.

### ISSUE THREAD

**Issue by rishi11** [abhimanyu1210/CS5610-abhi1210#1]
There should be 5 experiments every week. One is missing.

**Comment by abhi1210** [comment]
Hey Rishi,

Appreciate the feedback. But in the blog in week-3, I mentioned that the 5th experiment for that week was working on the home-page. If you feel the reason is appropriate, can you please close this issue?

**Comment by rishi11** [comment]
Create one page in experiment link and describe what you did on home page. Work on homepage will be considered as experiment.

**Comment by abhi1210** [comment]
Added a html page with iframe showing progress of home-page.
