### ISSUE TITLE
Story Utility Missing

### ISSUE THREAD

**Issue by rishi11** [abhimanyu1210/CS5610-abhi1210#3]
Experiments are not appearing in story utility format.

**Comment by abhi1210** [comment]
This week I have added story utility to all the experiments. I have attached screen-shot with this post. Can you please point out what am I missing?
![story_exp](https://cloud.githubusercontent.com/assets/5408663/6141978/0c15783e-b17c-11e4-988f-661230c894da.png)

**Comment by rishi11** [comment]
![screen shot 2015-02-10 at 11 31 28 pm](https://cloud.githubusercontent.com/assets/8660614/6142040/049b8bc4-b17d-11e4-9cbf-df40f30715ba.png)
Check on server. I might pe possible that you have not uploaded it.

**Comment by abhi1210** [comment]
Ohh! I get what the issue is. My link on the home-page with the picture on it does not have the story-utility associated with it. I story utility is on the "Experiments" link in the side-bar. If you want I can still edit the home-page image-link but I intentionally kept it like that.

**Comment by abhi1210** [comment]
Story-utility link added
