### ISSUE TITLE
Week04 : Experiment Not working

### ISSUE THREAD

**Issue by rishi11** [abhimanyu1210/CS5610-abhi1210#6]
Week 04 experiments are not working properly. 

Browser used : Google Chrome.

**Comment by abhi1210** [comment]
If you don't mind, can you please pin-point the error? There were a few images that had broken links. I have fixed that.

**Comment by rishi11** [comment]
http://net4.ccs.neu.edu/home/abhi1210/experiments/jqueryUI/000-jqueryUIEffects.html - Not able to drag.

http://net4.ccs.neu.edu/home/abhi1210/experiments/jqueryUI/001-jqueryUIWidgets.html - date picker and autocomplete

http://net4.ccs.neu.edu/home/abhi1210/experiments/API/000-webAPI.html

**Comment by abhi1210** [comment]
Hey,
I have fixed all the above issues. Can you please check? 
Issue: Jquery link was working fine on local but not on server.

**Comment by rishi11** [comment]
![screen shot 2015-02-18 at 1 15 51 am](https://cloud.githubusercontent.com/assets/8660614/6243266/cf97cbce-b70b-11e4-9f42-849fa10b38dd.png)
![screen shot 2015-02-18 at 1 16 27 am](https://cloud.githubusercontent.com/assets/8660614/6243270/d30eb45c-b70b-11e4-902d-aad5daec6af5.png)

Your webpage is showing these errors. Please resolve them

**Comment by abhi1210** [comment]
Hi Rishi,

This has been fixed. Closing Issue.
